# Generado por caelestia - no editar manualmente
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=#{{ onSurface.hex }},bg=default"
set -g status-left "#[fg=#{{ green.hex }},bold]  #S #[fg=#{{ onSurface.hex }},nobold] | "
set -g status-right "#[fg=#{{ green.hex }}]  #{cpu}   #{mem}  󱛟 #{disk -f}  󱊣 #{battery}  "
set -g window-status-current-format "#[fg=#{{ sky.hex }},bold] #[underscore]#I:#W#[nounderscore]#{?window_zoomed_flag, 󰍋 ,}"
set -g window-status-format " #I:#W"
set -g message-style "fg=#{{ onSurface.hex }},bg=default"
set -g mode-style "fg=#{{ surface0.hex }},bg=#{{ blue.hex }}"
set -g pane-border-style "fg=#{{ surface0.hex }}"
set -g pane-active-border-style "fg=#{{ green.hex }}"
