# Generado por caelestia - no editar manualmente
gray_light="#{{ onSurface.hex }}"
gray_medium="#{{ overlay0.hex }}"
gray_dark="#{{ surface0.hex }}"
green_soft="#{{ green.hex }}"
blue_muted="#{{ blue.hex }}"
cyan_soft="#{{ sky.hex }}"
