$primary_paletteKeyColor = 8e7167
$secondary_paletteKeyColor = 83746f
$tertiary_paletteKeyColor = b2aa8d
$neutral_paletteKeyColor = 7b7675
$neutral_variant_paletteKeyColor = 817470
$background = 050404
$onBackground = e8e1df
$surface = 050404
$surfaceDim = 050404
$surfaceBright = 101010
$surfaceContainerLowest = 030303
$surfaceContainerLow = 080707
$surfaceContainer = 090909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e8e1df
$surfaceVariant = 141313
$onSurfaceVariant = d3c3be
$inverseSurface = e8e1df
$inverseOnSurface = 33302f
$outline = 9c8e89
$outlineVariant = 4f4441
$shadow = 000000
$scrim = 000000
$surfaceTint = 292727
$primary = e2bfb3
$onPrimary = 412b23
$primaryContainer = c4a398
$onPrimaryContainer = 513931
$inversePrimary = 73584f
$secondary = d5c3bd
$onSecondary = 392e2a
$secondaryContainer = 514440
$onSecondaryContainer = c3b1ac
$tertiary = cfc6a8
$onTertiary = 35301b
$tertiaryContainer = 989175
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdbcf
$primaryFixedDim = e2bfb3
$onPrimaryFixed = 2a1710
$onPrimaryFixedVariant = 5a4139
$secondaryFixed = f2ded8
$secondaryFixedDim = d5c3bd
$onSecondaryFixed = 231916
$onSecondaryFixedVariant = 514440
$tertiaryFixed = ece2c3
$tertiaryFixedDim = cfc6a8
$onTertiaryFixed = 201c08
$onTertiaryFixedVariant = 4c4730
$term0 = 080808
$term1 = ff5717
$term2 = ffbe93
$term3 = ffdfd1
$term4 = b9ab66
$term5 = f2907d
$term6 = ffbb80
$term7 = efd3c6
$term8 = b49e95
$term9 = ff875f
$term10 = ffd5bb
$term11 = fff1ec
$term12 = dcbc93
$term13 = ffa996
$term14 = ffd3b1
$term15 = ffffff
$rosewater = ffeee9
$flamingo = ffdad0
$pink = ffd3cc
$mauve = ffaaa6
$red = ff9981
$maroon = faab97
$peach = ffbfa6
$yellow = ffeee6
$green = ffd9bb
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbbe
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5d56
$kvisitedSelection = cf5d59
$knegative = e9582b
$knegativeSelection = ea5731
$kneutral = ff8b58
$kneutralSelection = ff8b5d
$kpositive = f6900f
$kpositiveSelection = f88f17
$text = e8e1df
$subtext1 = d3c3be
$subtext0 = 9c8e89
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0d0d0d
$surface0 = 070606
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
